version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: bl_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: bl_worker
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bl_streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - worker
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app  # convenience: live-edit the app code locally

volumes:
  redis-data:
